### ISSUE TITLE
PyxelEditor broken ui

### ISSUE THREAD

**Issue by GitRenhl** [kitao/pyxel#103] opened 2018-11-21 17:43 UTC
Here is screenshot:

![obraz](https://user-images.githubusercontent.com/42244756/48858980-2464fc80-edbd-11e8-9082-a74e77f3dde5.png)
EDIT:
 - **Desktop:**
PC: Windows 10 Pro x64
RAM: 8GB
GPU: AMD R9 380 4GB
PYTHON: 3.6, 3.7.1
GLFW: 1.7.0
PyOpenGL: 3.1.1a1

**Comment by shivanju** [comment] 2018-11-21 20:05
Can you describe  your setup/platform?

**Comment by GitRenhl** [comment] 2018-11-21 22:31
@shivanju sorry, I forgot
PC: Windows 10 Pro x64
RAM: 8GB
GPU: AMD R9 380 4GB
PYTHON: 3.6

**Comment by shivanju** [comment] 2018-11-22 17:52
Didn't check with 3.6. I have 3.7.1 python installed and it works flawlessly. Rest of the things looks fine to me. Can you try upgrading your python once?

**Comment by GitRenhl** [comment] 2018-11-22 20:55
I just downloaded 3.7.1 and it's the same problem :/

**Comment by GitRenhl** [comment] 2018-11-22 21:20
I find something else. I wrote this code and here is the result:
```py
import pyxel
from pyxel.ui import TextButton

pyxel.init(255, 200)
pyxel.mouse(True)

btn = TextButton(None, 0, 0, "Simple Btn")

def update():
    btn._x, btn._y = pyxel.mouse_x - 20, pyxel.mouse_y - 5
    btn.update_widgets()

def render():
    pyxel.cls(0)
    btn.draw_widgets()

pyxel.run(update, render)

```
![pyxel-181122-220222](https://user-images.githubusercontent.com/42244756/48921943-7ed88880-eea3-11e8-862b-3bbf2e04b24a.gif)

**Comment by kitao** [comment] 2018-11-24 13:32
@GitRenhl Thank you! Your information is very helpful. I'll investigate the cause of this.

**Comment by kitao** [comment] 2018-11-29 12:57
@GitRenhl 
I couldn't reproduce this issue on my Mac and Windows yet.
Do you have any idea what cause this behavior?
It seems that the position of primitive is related...
Is is possible render the same size plain rectangle instead of the ui widget? 
I would also like to know the version of GLFW.

**Comment by GitRenhl** [comment] 2018-12-03 09:05
@kitao
GLFW: 1.7.0
PyOpenGL: 3.1.1a1

I don't know. Maybe there is a problem in glfw or AMD drivers.
I render try to render circles, rectangles, lines and images and they disappear when they are half out of the edge of the window as you can see here:
```py
import pyxel

WHITE = 7
RED = 8

class Item:
    def __init__(self, x, y, width=0, height=0):
        self.x = x
        self.y = y
        self.w = width
        self.h = height

    def move(self, x, y):
        self.x = x
        self.y = y

class App:
    def __init__(self):
        pyxel.init(100, 100)
        pyxel.mouse(True)

        self.item_r1 = Item(0, 0, 20, 20)
        self.item_r2 = Item(0, 0, 20, 20)
        self.item_r2sq = Item(self.item_r2.x, self.item_r2.y, 20, 5)

        self.item_c1 = Item(0, 0, 10)
        self.item_c2 = Item(0, 0, 10)

        pyxel.run(self.update, self.render)

    def update(self):
        pos = pyxel.mouse_x, pyxel.mouse_y

        self.item_r1.move(
            pos[0] - self.item_r1.w // 2,
            pos[1] - self.item_r1.h // 2 - self.item_r1.h - 5
        )  # TOP
        self.item_r2.move(
            pos[0] - self.item_r2.w // 2,
            pos[1] - self.item_r2.h // 2 + self.item_r2.h + 5
        )  # BOTTOM
        self.item_r2sq.move(
            self.item_r2.x,
            self.item_r2.y
        )  # BOTTOM 2

        self.item_c1.move(
            pos[0] - self.item_c1.w * 2,
            pos[1]
        )  # LEFT
        self.item_c2.move(
            pos[0] + self.item_c1.w * 2,
            pos[1]
        )  # RIGHT

    def render(self):
        pyxel.cls(0)

        pyxel.rect(
            self.item_r1.x, self.item_r1.y,
            self.item_r1.x + self.item_r1.w, self.item_r1.y + self.item_r1.h,
            WHITE
        )
        pyxel.rectb(
            self.item_r2.x, self.item_r2.y,
            self.item_r2.x + self.item_r2.w, self.item_r2.y + self.item_r2.h,
            WHITE
        )
        pyxel.rect(
            self.item_r2sq.x, self.item_r2sq.y,
            self.item_r2sq.x + self.item_r2sq.w, self.item_r2sq.y + self.item_r2sq.h,
            RED
        )
        pyxel.circ(self.item_c1.x, self.item_c1.y, self.item_c1.w, WHITE)
        pyxel.circb(self.item_c2.x, self.item_c2.y, self.item_c2.w, WHITE)

if __name__ == "__main__":
    App()
```
![pyxel-preview](https://user-images.githubusercontent.com/42244756/49363287-93a5ef00-f6e1-11e8-8f6e-8d01414bb3c0.gif)
I'll update graphic drivers this weekend and  check this issue again.

**Comment by kitao** [comment] 2018-12-08 02:19
@GitRenhl Thank you again!
Pyxel's rendering primitives consists of point sprites of OpenGL, and it seems that clipping area of point sprites cause this issue on some environments.

I'll continue to investigate the specification of point sprite clipping of OpenGL.

Actually I also have another plan to re-implement the rendering and audio low level functions with golang to improve performance. I'll continue to design for that too)

**Comment by kitao** [comment] 2018-12-09 07:56
This is my hypothesis:

Every drawing primitives of Pyxel is drawn as Point Sprite of OpenGL to reduce Python-OpenGL overhead. OpenGL's Point Sprite's shape is always square, so Pyxel calculates each primitive's virtual size and center position as square.

And I don't know why, but point sprite is clipped when its center position is outsize some clipping area (or screen area) on some environment. 

So if the position is close to the lower right of the screen and the shape is landscape or portrait, it is not drawn,  and if the size is relatively small, drawn because its center is inside clipping area.

By the way, Pyxel's text is drawn for each character, so its square size is very small and drawn well compared to other shapes.

**Comment by kitao** [comment] 2018-12-09 11:07
Unfortunately, it's the specification of OpenGL that when center of point sprite is outside the framebuffer, it will be clipped. So I added the margin area to the framebuffer for OpenGL rendering.

I confirmed this issue is fixed on my Linux environment of VirtualBox and released this version of Pyxel as 0.9.5.

@GitRenhl 
Could you check the latest version?

**Comment by kitao** [comment] 2018-12-09 11:12
And I know this is not the ideal design and it can be affected by OpenGL implementation. And I also noticed that iOS has the Point Sprite size limitation up to 32.

So I'll start developing native version of low level layer with golang or C seriously 
instead of using OpenGL Point Sprite hack.

**Comment by GitRenhl** [comment] 2018-12-10 10:18
@kitao Yes, everything render correctly now.

**Closed** 2018-12-10 12:52 UTC
Labels: bug
