### ISSUE TITLE
Installation fails on Windows 10 with Python 3.8

### ISSUE THREAD

**Issue by vincentxavier** [kitao/pyxel#424] opened 2022-10-12 12:51 UTC
On some Windows 10 computer with Python 3.8 preinstalled, installation fails for missing Rust/Cargo dependency. This should be at least mentionned on the installation page.

![image](https://user-images.githubusercontent.com/237506/195346678-6a1a3e9d-273e-4901-aee4-5e0adb8292d5.png)

I'll try to reinstall a newer version of Python, but these are government provided laptop for undergraduate student, with very low disk space and no Administrator access, so it could take a bit of time.

**Comment by vincentxavier** [comment] 2022-10-12 13:18
Yes, what kind of information do you need ?

**Comment by kitao** [comment] 2022-10-12 13:41
I confirmed Pyxel with both 32-bit and 64-bit version of Python on Windows 11 worked now.
So let me ask some questions.

The first question is your computer is 32-bit or 64-bit?
The second is what is the meaning of "preinstalled Python" ? Because Python is not preinstalled on Windows.
And the third is what the meaning of "low disk space" ?. Pyxel's binary size is not large and if you uninstall or delete the downloaded file, I think you can try another version of Pyxel.
I'm wondering if your environment is anything special different from the normal windows environment.

**Comment by messense** [comment] 2022-11-02 12:39
Some people might have accidentally configured `no-binary` for pip which disables wheel installation, see https://github.com/PyO3/maturin/issues/1211#issuecomment-1290278715

**Comment by vincentxavier** [comment] 2022-11-06 09:49
In a feww days, I should gain access to one of this computer, so I will investigate more closely.

**Comment by kitao** [comment] 2023-01-09 10:31
There's no other report. So I close this issue for now.

**Closed by kitao** 2023-01-09 10:31 UTC
