### ISSUE TITLE
Fullscreen mode on Macbook pro

### ISSUE THREAD

**Issue by kirberich** [kitao/pyxel#47] opened 2018-08-09 20:29 UTC
Hi! 

I'm loving this library and am planning to use it for a ludum dare this weekend, I found that fullscreen mode doesn't seem to work on my macbook pro though - when I press the shortcut to go fullscreen 
 I do get a fullscreen window, but whatever is currently drawn on the screen gets a bit distorted and then disappears, leaving just a black screen.

Is this is a known issue or something new? Where in the code could I look at debugging this?

**Comment by kitao** [comment] 2018-08-10 00:55
Hi, thank you for using Pyxel! I'm really happy if Pyxel is used in ludum.

This is unknown issue.
What Pyxel does is only calling full screen command of glfw.
Specifically, it is in `_toggle_fullscreen` method of app.py and window pos and size are set to `glfw.set_window_monitor` method.

I'm using MacBook and I don't any idea what is the difference between them.

First of all, I'll check thish is glfw's known issue or not.

**Comment by kitao** [comment] 2018-08-10 00:58
@kirberich By the way, Pyxel's window is resizable. So you can also press maximize button of the window. What happen if it is pressed in your environment?

**Comment by kirberich** [comment] 2018-08-10 13:25
So I've done a bit more fiddling with it and also tried recording a video, but unfortunately quicktime stops recording once the app goes fullscreen, so it's not very useful: https://www.youtube.com/watch?v=aZ9k-uHmsOU&feature=youtu.be

What I found is
- Resizing the window works fine
- Maximising the window also works fine
- Using the fullscreen button always fails.
- When coming back from fullscreen the window is still blank, but resizing the window fixes it.

Details about my machine and my dependencies:
- 15-inch macbook pro (late 2016) - it has a dedicated GPU (Radeon Pro 450), this might be where the difference between our laptops lies
- Python 3.6.5
- glfw==1.7.0
- pyxel==0.7.8
- PyOpenGL==3.1.0

I might have some time over the weekend to see if I can reproduce this problem in glfw directly!

**Comment by Jondyr** [comment] 2018-08-10 15:45
@kirberich You might want to check your glfw version and not only your wrappers version.

I tried to reproduce this on my MBP (Mid 2015, no dedicated GPU) and it works as expected.

Python 3.6.5
glfw: stable 3.2.1 (bottled), HEAD (wrapper 1.7.0)
Pyxel 0.7.8
PyOpenGL 3.1.0

**Comment by kitao** [comment] 2018-08-14 02:52
I added the glfw version check in Pyxel 0.7.9. At least, if glfw version is lower than expected, it raises a runtime error.

**Comment by kitao** [comment] 2018-10-16 23:16
Since there is no information update, close it. If you have any problems please create a new issue!

**Closed by kitao** 2018-10-16 23:16 UTC
Labels: bug, help wanted
