### ISSUE TITLE
Pyxel's text(x, y, string, color) function silently fails to print text to the screen.

### ISSUE THREAD

**Issue by mattjquinn** [kitao/pyxel#25] opened 2018-08-03 09:13 UTC
On my Debian buster machine I added a single call to Pyxel's text() function to the introductory example code in the README:

```
import pyxel

pyxel.init(160, 120)

def update():
    if pyxel.btnp(pyxel.KEY_Q):
        pyxel.quit()

def draw():
    pyxel.cls(0)
    pyxel.rect(10, 10, 20, 20, 11)
    pyxel.text(10, 10, "This is a sentence.", 11)

pyxel.run(update, draw)
```
and ran it, resulting in the following screenshot, which has the specified rectangle but the text is nowhere to be found:

![2018-08-03-120320_1600x900_scrot](https://user-images.githubusercontent.com/34240191/43634753-b36a0fc8-9715-11e8-8289-6a1178f5760a.png)

All apt packages installed successfully as required in the README:

```
Reading package lists...
Building dependency tree...
Reading state information...
libasound2-dev is already the newest version (1.1.6-1).
libglfw3 is already the newest version (3.2.1-1).
libportaudio2 is already the newest version (19.6.0-1).
python3-pip is already the newest version (9.0.1-2.3).
python3 is already the newest version (3.6.6-1).
0 upgraded, 0 newly installed, 0 to remove and 908 not upgraded.
```
and pip3 also had no errors installing required packages:

```
Collecting pyxel
  Using cached https://files.pythonhosted.org/packages/3d/2f/25879681cf00bc1d607322b4c59a3cfd768fa9b092910fde72194332ed34/pyxel-0.7.4-py3-none-any.whl
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from pyxel)
Collecting PyOpenGL (from pyxel)
Collecting sounddevice (from pyxel)
  Using cached https://files.pythonhosted.org/packages/fb/5d/0e6cf5ce99b99e76a24b573b94f9009d9d2f5cd13a73825d7e681c9a7a96/sounddevice-0.3.11-py2.py3-none-any.whl
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from pyxel)
Collecting glfw (from pyxel)
Collecting CFFI>=1.0 (from sounddevice->pyxel)
  Using cached https://files.pythonhosted.org/packages/6d/c0/47db8f624f3e4e2f3f27be03a93379d1ba16a1450a7b1aacfa0366e2c0dd/cffi-1.11.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting pycparser (from CFFI>=1.0->sounddevice->pyxel)
Installing collected packages: PyOpenGL, pycparser, CFFI, sounddevice, glfw, pyxel
Successfully installed CFFI-1.11.5 PyOpenGL-3.1.0 glfw-1.7.0 pycparser-2.18 pyxel-0.7.4 sounddevice-0.3.11
```

OS info is as follows:

```
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

I gave the text() function a look in the codebase but nothing stuck out at me as a potential issue, and no errors are printed to stdout/stderr when I run the above program.

**Comment by KevinVanKiwi** [comment] 2018-08-03 18:31
Just checked it on my system and it works for me, which is strange.
- Win10
- Python 3.6.2
- pyxel 0.7.4
![pyxel-180803-202815](https://user-images.githubusercontent.com/41760497/43659263-c6da57b6-975b-11e8-9c28-ff6b98a80866.png)

Code is the same:
```
import pyxel

pyxel.init(160, 120)

def update():
    if pyxel.btnp(pyxel.KEY_Q):
        pyxel.quit()

def draw():
    pyxel.cls(0)
    pyxel.rect(10, 10, 20, 20, 11)
    pyxel.text(10, 10, "This is a sentence.", 11)

pyxel.run(update, draw)
```

**Comment by kitao** [comment] 2018-08-04 10:33
@mattjquinn Hi, what will happen when the example #3 (draw api sample) runs on your environment?

**Comment by mattjquinn** [comment] 2018-08-04 11:00
Example #3 also has missing text. It also appears that clip() doesn't work either, though the screen changes colors and one of the sprites moves as expected:

![2018-08-04-135618_1600x900_scrot](https://user-images.githubusercontent.com/34240191/43675789-693d9558-97ee-11e8-9c6e-5eea6b5a0bb6.png)

Example #1 is also missing the top line of text as well:

![2018-08-04-135547_1600x900_scrot](https://user-images.githubusercontent.com/34240191/43675794-75630da4-97ee-11e8-9e6a-68c3c597eed6.png)

**Comment by matju** [comment] 2018-08-04 12:07
I have a similar issue issue - except I'm on MacOS Sierra. brew and pip3 installed everything OK.

In my case:

- Example 1 doesn't render any text
- Clipping doesn't work for Example 3
- Some fragments of text are rendered for Example 3 (see screenshot)
- Example 3's circles don't render properly

![pyxel-180804-130423](https://user-images.githubusercontent.com/42091194/43676329-0059a2ea-97e7-11e8-909b-b547612e5bfe.png)

**Comment by timbledum** [comment] 2018-08-05 21:31
Fine on my mac at home, but getting no text displayed on my windows 10 work computer. No install issues. Tried on 3.6 and 3.7, including fresh environment. 

![capture](https://user-images.githubusercontent.com/20265151/43690220-a7fa2410-995a-11e8-920f-6c76bb54f03e.PNG)

Do we have opengl version issues perhaps? I'm finding it hard to figure out what version is installed on windows though.

**Comment by matju** [comment] 2018-08-05 23:11
In my case I'm running MacOS 10.12.6 on a MacBook Pro (13-inch, 2016, Four Thunderbolt 3 ports) with Intel Iris Graphics 550 - apparently this supports OpenGL 4.1.

`brew list --versions` reports python 3.7.0 and glfw 3.2.1.

`pip3 list` reports: 
```
Package     Version
----------- -------
cffi        1.11.5 
glfw        1.7.0  
numpy       1.15.0 
Pillow      5.2.0  
pip         18.0   
pycparser   2.18   
PyOpenGL    3.1.0  
pyxel       0.7.6  
setuptools  40.0.0 
sounddevice 0.3.11 
wheel       0.31.1 
```

**Comment by kitao** [comment] 2018-08-06 01:38
@matju Appearently, you environment has enough specs to run Pyxel.

Now I'm wondering there is some informal OpenGL code and it causes this bug.

Could you try change line 139 of the example #3 from `pyxel.blt(x, y, 0, 0, 0, 16, 16)` to `pyxel.blt(x, y, 4, 0, 0, 16, 16)`?

By this change, Pyxel draws the system font texture with `blt` command.
If some characters with blue color are shown, it means the system font texture is available and the shader for `text` has some problem. If not, the system font texture has some problem.

**Comment by mattjquinn** [comment] 2018-08-06 04:53
@kitao Using OpenGL 4.2, I made the change to line 139; only difference was the first cat being replaced by a black square:

![2018-08-06-074258_1600x900_scrot](https://user-images.githubusercontent.com/34240191/43697380-8bed81bc-994c-11e8-9368-fdd8bc07a8f9.png)

Output of `glxinfo` is

```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 4.2 (Core Profile) Mesa 17.3.6
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.3.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```

Is there any advice you can give us for debugging issues with system font resources that Pyxel expects to be present?

**Comment by kitao** [comment] 2018-08-06 05:03
@mattjquinn Thank you! It seems that the image bank #5 of Pyxel is not available.
Potential possibility is your environment doesn't allow to use five textures at the same time, or shader setting of Pyxel for textures is informal OpenGL code.

If possible, could you change line.40 of constants.py of Pyxel from `RENDERER_IMAGE_COUNT = 5' to 'RENDERER_IMAGE_COUNT = 2'?

If the example #3 works by this change, the cause is the number of the texture unit.

**Comment by mattjquinn** [comment] 2018-08-06 05:12
No luck @kitao; after decreasing from 5 to 2, the only difference is that the background behind the first cat is gray:

![2018-08-06-081121_1600x900_scrot](https://user-images.githubusercontent.com/34240191/43698002-5f2949fa-9950-11e8-83db-40a49c04ac2b.png)

So you're saying that since this doesn't work, I should look into environment limitations on using five textures at the same time?

**Comment by kitao** [comment] 2018-08-06 05:16
@mattjquinn Sorry! You also need to the example #3.

Now, the System Font image number is 1, so please change the same line of the example #3 to `pyxel.blt(x, y, 1, 0, 0, 16, 16)`.

**Comment by matju** [comment] 2018-08-06 06:59
@kitao If I change line 139 of example 3 to `pyxel.blt(x, y, 4, 0, 0, 16, 16)` then the first cat is replaced with some faint blue text:

![pyxel-180806-073320](https://user-images.githubusercontent.com/42091194/43701533-74f7e13a-994e-11e8-85bd-a5ce44dbbd65.png)

**Comment by kitao** [comment] 2018-08-06 07:17
@matju Thank you for checking. This is the image I expected. So in your case, the number of the texture or size may be the cause. (Though I don't know it can cause breaking text rendering like this.)

Could you try to just change the `RENDERER_IMAGE_COUNT' of constant.py to some number less than 5 to make sure the number of the texture cause this?

**Comment by yeputons** [comment] 2018-08-06 16:11
Dirty hack that worked on my machine, see `shaders.py:327`:

```
-#define texture_color(index) int(texture2D(u_texture[index], uv).r * 255.0)
+#define texture_color(index) int(texture2D(u_texture[index], uv).r * 255.0 + 0.5)
```

My assumption is that the problem is that we texture values are floats between `0.0` and `1.0`, and we want to distinguish 1/255th. Unfortunately, 1/255 cannot be represented exactly and it turns out that `1/255 * 255` (via OpenGL) is rounded down to 0 on my machine. This effect can be also noted when rendering images with `blt`. Say, color 1 becomes 0, 2 becomes 1, 4 becomes 3.

I'm not exactly sure what causes that effect or even what are exact values returned by `texture2D() * 255.0` instead of `1.0`. I think it should be something like `0.9999`, but I haven't checked and recommend further investigation (a hotfix may be landed in the meantime).

cc @olgalupuleac

**Comment by kitao** [comment] 2018-08-06 23:13
Hi, @yeputons 
Thank you for good information! I understood what happen in your environment.
So in your environment, all color drawn with `blt` and `text` command changes rather than text is not drawn?

**Comment by yeputons** [comment] 2018-08-07 07:19
@kitao Color drawn with `blt` changes, yes, but `text` is not drawn at all: font is passed through a texture with 0/1 values, and 1 gets rounded down to 0 in `texture_color`, so the shader assumes that all pixels are zero and does not draw anything.

**Comment by kitao** [comment] 2018-08-07 14:45
@yeputons  I imported your modification in v0.7.8. I hope it works in your environment.

**Comment by timbledum** [comment] 2018-08-07 23:00
This fixed it for me!

**Comment by kitao** [comment] 2018-08-07 23:11
Good!

**Comment by mattjquinn** [comment] 2018-08-08 08:09
Yes fixed for me as well.

**Closed** 2018-08-08 09:27 UTC
Labels: bug

**Comment by matju** [comment] 2018-08-08 21:46
Sorry to disappoint but I have the same problem in Pyxel 0.7.8...

![pyxel-180808-234521](https://user-images.githubusercontent.com/42091194/43866200-2f466c60-9b65-11e8-87f4-eb2ea29cd247.png)

```
$ pip3 list
Package     Version
----------- -------
cffi        1.11.5 
glfw        1.7.0  
numpy       1.15.0 
Pillow      5.2.0  
pip         18.0   
pycparser   2.18   
PyOpenGL    3.1.0  
pyxel       0.7.8  
setuptools  40.0.0 
sounddevice 0.3.11 
wheel       0.31.1 
```

**Comment by kitao** [comment] 2018-08-08 22:05
@matju In your case, texts are drawn partially and circles are not drawn. So I split your case as #45 
Let me ask more information in #45
